root_path: C:\Users\User\Documents\Cars_processing
logging_level: INFO
column_mappings:
  'offer_name': 'offer_name'
  'price': 'price'
  'seller': 'seller'
  'description': 'description'
  'Pokaz oferty z numerem VIN': 'show_VIN'
  'Ma numer rejestracyjny': 'regisered'
  'Marka pojazdu': 'brand'
  'Model pojazdu': 'model'
  'Wersja': 'version'
  'Rok produkcji': 'production_year'
  'Przebieg': 'mileage'
  'Pojemnosc skokowa': 'displacement'
  'Rodzaj paliwa': 'fuel_type'
  'Moc': 'power'
  'Skrzynia biegow': 'gearbox'
  'Naped': 'drive'
  'Typ nadwozia': 'body_type'
  'Liczba drzwi': 'doors_number'
  'Liczba miejsc': 'seats_number'
  'Kolor': 'color'
  'Rodzaj koloru': 'color_type'
  'Mozliwosc finansowania': 'financing_options'
  'Faktura VAT': 'vat_invoice'
  'Leasing': 'leasing'
  'Okres gwarancji producenta': 'producer_warranty_period'
  'lub do (przebieg km)': 'producer_warranty_milage'
  'Kraj pochodzenia': 'country_of_origin'
  'Data pierwszej rejestracji w historii pojazdu': 'first_regisered_date'
  'Numer rejestracyjny pojazdu': 'registration_number'
  'Zarejestrowany w Polsce': 'registered_in_poland'
  ' Pierwszy wasciciel (od nowosci)': 'first_owner'
  'Bezwypadkowy': 'no_collisions'
  'Serwisowany w ASO': 'ASO_serviced'
  'Stan': 'condition'
  'Uszkodzony': 'damaged'
  'VAT marza': 'VAT_marigin'
  'Gwarancja dealerska (w cenie)': 'dealer_warranty'
  'Emisja CO2': 'CO2_emission'
  'Spalanie W Miescie': 'fuel_consumption_city'
  'Spalanie Poza Miastem': 'fuel_consumption_outside_city'
  'Spalanie W Cyklu Mieszanym': 'fuel_consumption_city_and_outsite'
  'Miesieczna rata': 'monthly_payment'
  'Opata poczatkowa': 'initial_payment'
  'Wartosc wykupu': 'redemption_value'
  'Liczba pozostaych rat': 'monthly_payments_remaining'
  'Isofix (punkty mocowania fotelika dzieciecego)': 'isofix'
  'Poduszka powietrzna pasazera': 'airbags' 
  'Poduszka powietrzna kierowcy': 'airbags' 
  'Boczna poduszka powietrzna kierowcy': 'airbags_front' 
  'Boczne poduszki powietrzne - przod': 'airbags_front'
  'Kurtyny powietrzne - przod': 'airbags_front' 
  'Poduszki powietrzne czoowe - ty': 'airbags_rear'
  'Boczne poduszki powietrzne - ty': 'airbags_rear'
  'Kurtyny powietrzne - ty': 'airbags_rear' 
  'Kurtyna powietrzna z tyu, poprzeczna': 'airbags_rear'
  'Poduszka powietrzna centralna': 'airbag_central'
  'Poduszka powietrzna pasow bezpieczenstwa': 'airbag'
  'Poduszka kolan pasazera': 'passenger_knee_airbag'
  'Poduszka kolan kierowcy': 'driver_knee_airbag'
  'ESP': 'ESP' 
  'Ogranicznik predkosci': 'speed_limiter' 
  'ABS': 'ABS' 
  'Podgrzewany fotel pasazera': 'heated_passanger_seat' 
  'Elektryczne szyby tylne': 'electric_rear_windows' 
  'Ekran dotykowy': 'touchscreen' 
  'System powiadamiania o wypadku': 'accident_notification_system' 
  'System ochrony suchu w przypadku kolizji': 'collision_protection_system'
  'System chroniacy przed kolizja: tylny': 'collision_protection_system'
  'System chroniacy przed kolizja, tylny': 'collision_protection_system'
  'Asystent zapobiegania kolizjom na skrzyzowaniu': 'collision_protection_system'
  'System chroniacy przed kolizja, boczny': 'collision_protection_system'
  'Aktywny asystent hamowania awaryjnego': 'emergency_braking_system' 
  'System ostrzegajacy o mozliwej kolizji': 'emergency_braking_system' 
  'System hamowania awaryjnego dla ochrony pieszych': 'emergency_braking_system' 
  'System minimalizujacy skutki kolizji': 'emergency_braking_system'
  'Asystent hamowania awaryjnego w miescie': 'emergency_braking_system'
  'Asystent hamowania - Brake Assist': 'emergency_braking_system'
  'System wspomagania hamowania': 'emergency_braking_system' 
  'Elektroniczny system rozdziau siy hamowania': 'electric_parking_brake'
  'System rekomendacji przerw podczas trasy': 'driver_fatigue_detection_system' 
  'System wykrywania zmeczenie kierowcy': 'driver_fatigue_detection_system'
  'Aktywny system monitorowania kondycji kierowcy': 'driver_fatigue_detection_system'
  'System odzyskiwania energii': 'energy_recovery_system'
  'System zabezpieczajacy podczas dachowania': 'rollover_protection_system'
  'System rozpoznawania znakow drogowych': 'traffic_sign_recognition_system'
  'Aktywne rozpoznawanie znakow ograniczenia predkosci': 'traffic_sign_recognition_system'
  'Sterowanie funkcjami pojazdu za pomoca gosu': 'voice_control_system'
  'Podgrzewane lusterka boczne': 'heated_side_mirrors'
  'Zestaw gosnomowiacy' : 'hands_free_kit ' 
  'Kontrola odlegosci od poprzedzajacego pojazdu': 'forward_vehicle_distance_control' 
  'Felgi stalowe': 'steel_wheels'
  'Felgi aluminiowe 16': 'aluminum_wheels_16' 
  'Felgi aluminiowe 17': 'aluminum_wheels_17'
  'Felgi aluminiowe 18': 'aluminum_wheels_18'
  'Felgi aluminiowe 19': 'aluminum_wheels_19'
  'Podokietniki - ty': 'rear_armrests' 
  'Kierownica wielofunkcyjna': 'multifunction_steering_wheel' 
  'Kierownica ze sterowaniem radia': 'multifunction_steering_wheel' 
  'Zmiana biegow w kierownicy': 'steering_wheel_gear_shift'
  'Kierownica skorzana': 'leather_steering_wheel'
  'Kierownica sportowa': 'leather_steering_wheel'
  'Kierownica ogrzewana': 'heated_steering_wheel'
  'Wspomaganie kierownicy': 'power_steering'
  'Kolumna kierownicy regulowana elektrycznie': 'power_steering'
  'Tapicerka czesciowo skorzana': 'leather_upholstery'
  'Tapicerka skorzana': 'leather_upholstery'
  'Tapicerka materiaowa': 'fabric_upholstery' 
  'Tapicerka Alcantara': 'fabric_upholstery'
  'System nagosnienia': 'sound_system' 
  'Kontrola odlegosci z przodu (przy parkowaniu)': 'front_parking_distance_control' 
  'Kontrola odlegosci z tyu (przy parkowaniu)': 'rear_parking_distance_control' 
  'Alarm ruchu poprzecznego z tyu pojazdu': 'rear_parking_distance_control'
  'Kamera parkowania ty': 'rear_parking_camera'
  'Park Assistant - asystent parkowania': 'park_assistant'
  'Niezalezny system parkowania': 'park_assistant'
  'Podokietniki - przod': 'front_armrests' 
  'Wspomaganie ruszania pod gore- Hill Holder': 'hill_holder' 
  'Lusterka boczne ustawiane elektrycznie': 'electrically_adjustable_side_mirrors' 
  'Apple CarPlay': 'apple_carplay' 
  'Android Auto': 'android_auto' 
  'Lane assist - kontrola zmiany pasa ruchu': 'lane_assist' 
  'Aktywny asystent zmiany pasa ruchu': 'lane_assist'
  'Asystent pasa ruchu': 'lane_assist'
  'Kamera w lusterku bocznym': 'lane_assist'
  'Podgrzewany fotel kierowcy': 'heated_driver_seat ' 
  'Elektryczne szyby przednie': 'electric_front_windows' 
  'Gniazdo USB': 'usb_socket'  
  'Dzwignia zmiany biegow wykonczona skora': 'leather_gear_shift' 
  'Tempomat adaptacyjny ACC': 'adaptive_cruise_control_acc'
  'Tempomat': 'adaptive_cruise_control_acc'
  'Asystent jazdy w korku': 'adaptive_cruise_control_acc'
  'Autonomiczny system kierowania': 'adaptive_cruise_control_acc'
  'Tempomat przewidujacy PCC': 'Tempomat przewidujacy PCC'
  'Radio': 'radio' 
  'Klimatyzacja manualna': 'manual_air_conditioning' 
  'System Start/Stop': 'start_stop_system' 
  'Kontrola trakcji': 'traction_control' 
  'Interfejs Bluetooth': 'bluetooth_interface'
  'Swiata do jazdy dziennej': 'daytime_running_lights'
  'Klimatyzacja automatyczna': 'automatic_air_conditioning'
  'Klimatyzacja automatyczna, dwustrefowa': 'automatic_air_conditioning'
  'Automatyczna kontrola ogrzewania': 'automatic_air_conditioning'
  'Czujnik deszczu': 'rain_sensor'
  'Lampy ksenonowe': 'xenon_headlights'
  'Swiata do jazdy dziennej diodowe LED': 'led_headlights' 
  'Lampy przednie w technologii LED': 'led_headlights'
  'Reflektory laserowe': 'led_headlights'
  'Lampy przeciwmgielne': 'fog_lights'
  'Lampy przeciwmgielne w technologii LED': 'fog_lights'
  'Lampy tylne w technologii LED': 'led_tail_lights'
  'Oswietlenie wnetrza LED': 'led_interior_lighting'
  'Lampy doswietlajace zakret': 'cornering_lights'
  'Klimatyzacja dla pasazerow z tyu': 'rear_passenger_air_conditioning'
  'Oswietlenie drogi do domu': 'home_pathway_lighting'
  'Czujnik zmierzchu': 'dusk_sensor'
  'Wycieraczki': 'windshield_wipers'
  'Elektroniczna kontrola cisnienia w oponach': 'electronic_tire_pressure_control'
  'Lusterka boczne skadane elektrycznie': 'electrically_foldable_side_mirrors'
  'Dynamiczne swiata doswietlajace zakrety': 'cornering_lights'
  'Asystent pokonywania zakretow': 'cornering_lights'
  'Opony runflat': 'run_flat_tyres'
  'Opony zimowe': 'winter_tyres'
  'Opony letnie': 'summer_tyres'
  'Opony wielosezonowe': 'all_season_tyres'
  'Klimatyzacja automatyczna: dwustrefowa': 'dual_zone_automatic_air_conditioning'
  'Asystent (czujnik) martwego pola': 'blind_spot_sensor'
  'Przyciemniane tylne szyby': 'tinted_rear_windows'
  'Dostep do internetu': internet_access
  'Oswietlenie adaptacyjne': 'adaptive_lighting'
  'Spryskiwacze reflektorow': 'headlight_washers'
  'Asystent swiate drogowych': 'high_beam_assist'
  'Elektryczny hamulec postojowy': 'electric_parking_brake'
  'Automatyczna kontrola zjazdu ze stoku': 'electric_parking_brake'
  'Keyless entry': 'keyless_entry'
  'Cyfrowy kluczyk': 'keyless_entry'
  'Keyless Go': 'keyless_go '
  'Uruchamianie silnika bez uzycia kluczykow': 'keyless_engine_start' 
  'System nawigacji satelitarnej': 'satellite_navigation_system'
  'adowanie bezprzewodowe urzadzen': 'wireless_device_charging'
  'Regul. elektr. podparcia ledzwiowego - pasazer': 'electric_lumbar_support_adjustment_passenger'
  'Regul. elektr. podparcia ledzwiowego - kierowca': 'electric_lumbar_support_adjustment_driver'
  'Elektrycznie ustawiany fotel kierowcy': 'electric_seat_adjustment_passenger'
  'Zawieszenie komfortowe': 'comfort_suspension'
  'Zawieszenie sportowe': 'sport_suspension'
  'Filtr czastek staych': 'particulate_filter'
  'Sportowe fotele - przod': 'sport_front_seats'
  'Podgrzewana przednia szyba': 'heated_front_windshield'
  'Blokada mechanizmu roznicowego': 'differential_lock'
  'Hak': 'tow_hook'
  'System emitujacy dzwiek silnika (AVAS)': 'AVAS'
